baseURL = "https://epic-bartik-2bb8a0.netlify.app/"
title = "Robert's Blog"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

disableKinds = ["RSS"]

[params]
  description = "Posting on the Internet is fun!"
  copyright = "Copyright © 2020 Robert Liu"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true
